spring:
  config:
    activate:
      on-profile: default

server:
  port: 8888

rethinkdb:
  host: localhost
  port: 28015
  database: productDB
  table: product
  username: admin
  password:

logbook:
  include:
    - /v1/product/**
  filter.enabled: true
  secure-filter.enabled: true
  obfuscate:
    headers:
    parameters:

logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE